DATA_SPACE:
    MODULE: physion.data_space
    SEEDS: [0,1,2]
    KWARGS:
        scenarios: ['Collide', 'Contain', 'Dominoes', 'Drape', 'Drop', 'Link', 'Roll', 'Support']
        file_pattern: '*.hdf5'
        pretraining:
            train:
                dir: 'physion_data/pretraining_train'
            test:
                dir: 'physion_data/pretraining_val'
        readout:
            train:
                dir: 'physion_data/readout_train_redyellow'
            test:
                dir: 'physion_data/readout_test_redyellow'
        pretraining_protocols: ['all']
        readout_protocol: 'full'

PRETRAINING:
    OBJECTIVE_MODULE: physion.objective.CSWM
    MODEL_NAME: 'CSWM'
    TRAIN_STEPS: 1000
    BATCH_SIZE: 32
    VAL_FREQ: 1000
    CKPT_FREQ: 100
    TRAIN:
        LR: 5.e-4
    MODEL: 
        ENCODER: 'medium'
        SIGMA: 0.5
        HINGE: 1. 
        HIDDEN_DIM: 512
        EMBEDDING_DIM: 128
        NUM_OBJECTS: 10
        ACTION_DIM: 0 
        IGNORE_ACTION: True
    DATA:
        STATE_LEN: 7
        SEQ_LEN: 25
        IMSIZE: 224
        SUBSAMPLE_FACTOR: 6

EXTRACTION:
    OBJECTIVE_MODULE: physion.objective.CSWM

READOUT:
    MODEL: {}
    PROTOCOLS: ['simulated']

CONFIG:
    POSTGRES: {}
