DATA_SPACE:
    MODULE: physion.data_space
    SEEDS: [0]
    KWARGS:
        scenarios: ['Collide', 'Contain', 'Dominoes', 'Drape', 'Drop', 'Link', 'Roll', 'Support']
        pretraining:
            train:
                dir: 'physion_data/pretraining_train'
            test:
                dir: 'physion_data/pretraining_val'
        readout:
            train:
                dir: 'physion_data/readout_train_redyellow'
            test:
                dir: 'physion_data/readout_test_redyellow'
        pretraining_protocols: ['all']
        readout_protocol: 'minimal'

PRETRAINING:
    OBJECTIVE_MODULE: physion.objective.CSWM
    MODEL_NAME: 'CSWM'
    TRAIN_STEPS: 100000
    BATCH_SIZE: 512
    VAL_FREQ: 1000
    CKPT_FREQ: 1000
    TRAIN:
        LR: 5.e-4
    MODEL: 
        # ENCODER: 'medium'
        ENCODER: 'fitvid'
        SIGMA: 0.5
        HINGE: 1. 
        HIDDEN_DIM: 512
        EMBEDDING_DIM: 128
        NUM_OBJECTS: 10
        ACTION_DIM: 0 
        IGNORE_ACTION: True
    DATA:
        STATE_LEN: 7
        SEQ_LEN: 25
        IMSIZE: 64
        SUBSAMPLE_FACTOR: 6

EXTRACTION:
    OBJECTIVE_MODULE: physion.objective.CSWM
    LOAD_STEP: 34000
SKIP_PRETRAINING: True

READOUT:
    PROTOCOLS: ['simulated', 'observed', 'input']

CONFIG:
    EXPERIMENT_NAME: 'physion-cswm-fitvid'
    POSTGRES:
        DBNAME: 'physion-physopt'
