DATA_SPACE:
    MODULE: physion.data_space
    SEEDS: (0,)
    KWARGS:
        pretraining_train_dir: 'physion_data/pretraining_train'
        pretraining_test_dir: 'physion_data/pretraining_val'
        pretraining_scenarios: ('Collide', 'Contain', 'Dominoes', 'Drape', 'Drop', 'Link', 'Roll', 'Support')
        pretraining_protocols: ('only', 'abo', 'all')
        readout_train_dir: 'physion_data/readout_train_redyellow'
        readout_test_dir: 'physion_data/readout_test_redyellow'
        readout_protocol: 'minimal'

PRETRAINING:
    OBJECTIVE_MODULE: physion.objective.FROZEN
    MODEL_NAME: 'pDEIT_MLP'
    TRAIN_STEPS: 100
    BATCH_SIZE: 32
    TRAIN:
        LR: 1.e-2
    DATA:
        STATE_LEN: 7
        SEQ_LEN: 25
        IMSIZE: 224
        SUBSAMPLE_FACTOR: 6

EXTRACTION:
    OBJECTIVE_MODULE: physion.objective.FROZEN

CONFIG:
    EXPERIMENT_NAME: 'physion'
    POSTGRES:
        DBNAME: 'physion-physopt'
