DATA_SPACE:
    MODULE: physion.data_space
    SEEDS: (0,)
    KWARGS:
        scenarios: ['Collide_debug2'] 
        pretraining:
            train:
                dir: 'physion_data/pretraining_train'
            test:
                dir: 'physion_data/pretraining_train'
                # dir: 'physion_data/pretraining_val'
        readout:
            train:
                dir: 'physion_data/pretraining_train'
                # dir: 'physion_data/readout_train_redyellow'
            test:
                dir: 'physion_data/pretraining_train'
                # dir: 'physion_data/readout_test_redyellow'
        pretraining_protocols: ['only']
        # pretraining_protocols: ['all']
        readout_protocol: 'minimal'

SKIP_PRETRAINING: True
PRETRAINING:
    OBJECTIVE_MODULE: physion.objective.FitVid
    MODEL_NAME: 'FitVid'
    TRAIN_STEPS: 100000
    BATCH_SIZE: 8
    TRAIN:
        LR: 1.e-4
    MODEL:
        z_dim: 10
        beta: 1.e-4
        # g_dim: 32
        # rnn_size: 64
        # num_channels: 16
        g_dim: 128
        rnn_size: 256
        num_channels: 64
    DATA:
        STATE_LEN: 7
        SEQ_LEN: 25
        IMSIZE: 64
        SUBSAMPLE_FACTOR: 6

EXTRACTION:
    OBJECTIVE_MODULE: physion.objective.FitVid
    LOAD_STEP: 65200

READOUT:
    # PROTOCOLS: ['simulated']
    PROTOCOLS: ['simulated', 'observed']

CONFIG:
    EXPERIMENT_NAME: 'physion-fitvid'
    POSTGRES:
        DBNAME: 'physion-physopt'
