DATA_SPACE:
    MODULE: physion.data_space
    SEEDS: (0,)
    KWARGS:
        # scenarios: ['Collide', 'Contain', 'Dominoes', 'Drape', 'Drop', 'Link', 'Roll', 'Support']
        scenarios: ['Drop'] 
        pretraining:
            train:
                dir: 'physion_data/pretraining_train'
            test:
                dir: 'physion_data/pretraining_val'
        readout:
            train:
                # dir: 'physion_data/pretraining_train'
                dir: 'physion_data/readout_train_redyellow'
            test:
                dir: 'physion_data/readout_test_redyellow'
        pretraining_protocols: ['only']
        # pretraining_protocols: ['all']
        readout_protocol: 'minimal'

# SKIP_PRETRAINING: True
PRETRAINING:
    VAL_FREQ: 5000
    CKPT_FREQ: 5000
    OBJECTIVE_MODULE: physion.objective.FitVid
    MODEL_NAME: 'FitVid'
    TRAIN_STEPS: 1000000
    BATCH_SIZE: 16
    TRAIN:
        LR: 1.e-3
        ACCUMULATION_BATCH_SIZE: 128
    MODEL:
        z_dim: 10
        beta: 1.e-4
        g_dim: 128
        rnn_size: 256
        num_channels: 64
    DATA:
        IMSIZE: 64
        # STATE_LEN: 7
        # SEQ_LEN: 25
        # SUBSAMPLE_FACTOR: 6
        STATE_LEN: 5
        SEQ_LEN: 16
        SUBSAMPLE_FACTOR: 9

EXTRACTION:
    OBJECTIVE_MODULE: physion.objective.FitVid
    # LOAD_STEP: 90000

READOUT:
    # PROTOCOLS: ['simulated']
    PROTOCOLS: ['simulated', 'observed']

CONFIG:
    EXPERIMENT_NAME: 'physion-fitvid'
    POSTGRES:
        DBNAME: 'physion-physopt'
