name: pytorch_v17
channels:
  - pytorch
  - fastai
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - addict=2.3.0=py36h5fab9bb_2
  - albumentations=1.0.3=py_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py36_1
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py36h8f6f2f9_1001
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.2=h7f98852_0
  - ca-certificates=2021.5.30=ha878542_0
  - cairo=1.14.12=h8948797_3
  - certifi=2021.5.30=py36h5fab9bb_0
  - cffi=1.14.6=py36hd8eec40_1
  - chardet=4.0.0=py36h5fab9bb_1
  - charset-normalizer=2.0.0=pyhd8ed1ab_0
  - cloudpickle=1.6.0=py_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - conda=4.10.3=py36h5fab9bb_1
  - conda-package-handling=1.7.3=py36h8f6f2f9_0
  - cryptography=3.4.7=py36hb60f036_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - cycler=0.10.0=py36_0
  - cytoolz=0.11.0=py36h7b6447c_0
  - dask-core=2.30.0=py_0
  - dataclasses=0.7=py36_0
  - dbus=1.13.18=hb2f20db_0
  - decorator=4.4.2=py_0
  - entrypoints=0.3=py36h9f0ad1d_1002
  - expat=2.2.10=he6710b0_2
  - fastcore=1.3.26=py_0
  - fastprogress=1.0.0=pyh39e3cac_0
  - ffmpeg=4.0=hcdf2ecd_0
  - fire=0.4.0=pyh44b312d_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.10.4=h5ab3b9f_0
  - glib=2.56.2=hd408876_0
  - graphite2=1.3.14=h23475e2_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=he6710b0_3
  - idna=3.1=pyhd3deb0d_0
  - imageio=2.9.0=py_0
  - intel-openmp=2020.2=254
  - ipykernel=5.5.5=py36hcb3619a_0
  - ipython=7.16.1=py36he448a4c_2
  - ipython_genutils=0.2.0=py36_0
  - jasper=2.0.14=h07fcdf6_1
  - jbig=2.1=h7f98852_2003
  - jedi=0.17.2=py36h5fab9bb_1
  - joblib=1.0.1=pyhd8ed1ab_0
  - jpeg=9d=h36c2ea0_0
  - jupyter_client=7.0.2=pyhd8ed1ab_0
  - jupyter_core=4.8.1=py36h5fab9bb_0
  - kiwisolver=1.2.0=py36hfd86e86_0
  - kornia=0.3.0=pyh9f0ad1d_0
  - krb5=1.19.2=hcc1bbae_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=2.2.1=h9c3ff4c_0
  - libarchive=3.5.2=hccf745f_0
  - libcurl=7.79.0=h2574ce0_0
  - libdeflate=1.7=h7f98852_5
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h9c3ff4c_1
  - libgcc-ng=11.2.0=h1d223b6_8
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libgomp=11.2.0=h1d223b6_8
  - libiconv=1.16=h516909a_0
  - libjpeg-turbo=2.1.0=h7f98852_0
  - libnghttp2=1.43.0=h812cca2_0
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsolv=0.7.19=h780b84a_5
  - libssh2=1.10.0=ha56f1ee_0
  - libstdcxx-ng=11.2.0=he4da1e4_8
  - libtiff=4.3.0=hf544144_1
  - libuuid=1.0.3=h1bed415_2
  - libuv=1.40.0=h7b6447c_0
  - libvpx=1.7.0=h439df22_0
  - libwebp-base=1.2.1=h7f98852_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - lzo=2.10=h516909a_1000
  - mamba=0.15.3=py36h05d92e0_0
  - matplotlib=3.3.1=0
  - matplotlib-base=3.3.1=py36h817c723_0
  - mkl=2020.2=256
  - mkl_fft=1.0.6=py36h7dd41cf_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - ncurses=6.2=h58526e2_4
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - networkx=2.5=py_0
  - ninja=1.10.1=py36hfd86e86_0
  - numpy-base=1.15.4=py36h81de0dd_0
  - olefile=0.46=py36_0
  - opencv=3.4.2=py36h6fd60c2_1
  - opencv-python-headless=4.5.3.56=py36_0
  - openssl=1.1.1l=h7f98852_0
  - packaging=21.0=pyhd8ed1ab_0
  - pandas=1.1.3=py36he6710b0_0
  - parso=0.7.1=pyh9f0ad1d_0
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=py36h9f0ad1d_1
  - pickleshare=0.7.5=py36h9f0ad1d_1002
  - pillow=8.0.0=py36h9a89aac_0
  - pip=21.2.4=pyhd8ed1ab_0
  - pixman=0.40.0=h7b6447c_0
  - prompt-toolkit=3.0.20=pyha770c72_0
  - psutil=5.7.2=py36h7b6447c_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - py-opencv=3.4.2=py36hb342d67_1
  - pycosat=0.6.3=py36h8f6f2f9_1006
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.10.0=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.9.2=py36h05f1152_2
  - pysocks=1.7.1=py36h5fab9bb_3
  - python=3.6.13=hb7a2778_1_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=2_cp36m
  - pytorch=1.7.0=py3.6_cuda10.2.89_cudnn7.6.5_0
  - pytz=2020.1=py_0
  - pywavelets=1.1.1=py36h7b6447c_2
  - pyyaml=5.3.1=py36h7b6447c_1
  - pyzmq=22.3.0=py36h7068817_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h46c0cb4_0
  - reproc=14.2.3=h7f98852_0
  - reproc-cpp=14.2.3=h9c3ff4c_0
  - requests=2.26.0=pyhd8ed1ab_0
  - ruamel_yaml=0.15.80=py36h8f6f2f9_1004
  - scikit-image=0.16.2=py36h0573a6f_0
  - scipy=1.1.0=py36hfa4b5c9_1
  - seaborn=0.11.0=py_0
  - setuptools=58.0.4=py36h5fab9bb_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.36.0=h9cd32fc_1
  - termcolor=1.1.0=py36_1
  - tk=8.6.11=h27826a3_1
  - toolz=0.11.1=py_0
  - torchaudio=0.7.0=py36
  - torchvision=0.8.0=py36_cu102
  - tornado=6.0.4=py36h7b6447c_1
  - tqdm=4.62.2=pyhd8ed1ab_0
  - traitlets=4.3.3=py36h9f0ad1d_1
  - typing_extensions=3.7.4.3=py_0
  - urllib3=1.26.6=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.37.0=pyhd8ed1ab_1
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zlib=1.2.11=h516909a_1010
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - future==0.18.2
    - madgrad==1.1
    - numpy==1.19.5
    - pillow-simd==7.0.0.post3
    - pyturbojpeg==1.1.2
prefix: /n/home02/alvarez/.conda/envs/pytorch_v17
